-- CWD Stage 3 additive architecture migration
-- 2026-08-31
--
-- Purpose:
--   Add the persistent, versioned structures required by the approved
--   Confidence-Weighted Response (CWD) Stage 3 architecture while preserving
--   all legacy tables/columns for compatibility and rollback.
--
-- This migration is intentionally non-destructive:
--   * no legacy columns are dropped;
--   * the legacy responses table is retained;
--   * existing server/frontend code can continue to operate until the
--     application is explicitly switched to the Stage 3 path;
--   * repository location is not treated as proof of current model identity;
--   * a new canonical CWD development row is added inactive alongside the
--     legacy row rather than rewriting that legacy row in place;
--   * keyed activities must never acquire answer disclosure automatically.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Extend activity identity with a versioned semantic configuration object.
-- ---------------------------------------------------------------------------

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS model TEXT;

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS variant TEXT;

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS config JSONB;

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS schema_version INTEGER;

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Current CWD Stage 3 scope is deliberately bounded to the two validated
-- social variants. A row classified as CWD must carry a versioned config.
ALTER TABLE activities
  DROP CONSTRAINT IF EXISTS chk_cwd_stage3_contract;

ALTER TABLE activities
  ADD CONSTRAINT chk_cwd_stage3_contract
  CHECK (
    model IS DISTINCT FROM 'confidence_weighted_response'
    OR (
      variant IN ('social_immediate', 'social_delayed')
      AND config IS NOT NULL
      AND schema_version IS NOT NULL
    )
  );

-- ---------------------------------------------------------------------------
-- 2. Reusable confidence-scale registry.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS confidence_scales (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  points JSONB NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_confidence_scale_points_array
    CHECK (jsonb_typeof(points) = 'array')
);

INSERT INTO confidence_scales (id, name, points, schema_version, active)
VALUES (
  'confidence_5',
  'Five-point confidence scale',
  '[
    {"value":1,"label":"Not at all confident"},
    {"value":2,"label":"Slightly confident"},
    {"value":3,"label":"Moderately confident"},
    {"value":4,"label":"Very confident"},
    {"value":5,"label":"Extremely confident"}
  ]'::jsonb,
  1,
  true
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Persistent classroom/session orchestration.
-- ---------------------------------------------------------------------------
-- UUID values are generated by the application layer (Node crypto.randomUUID)
-- rather than requiring a PostgreSQL extension.

CREATE TABLE IF NOT EXISTS activity_sessions (
  id UUID PRIMARY KEY,
  activity_id TEXT NOT NULL REFERENCES activities(id),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revealed_at TIMESTAMPTZ,
  resolution_opened_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  expected_cohort_size INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_session_cohort_size
    CHECK (expected_cohort_size IS NULL OR expected_cohort_size > 0),
  CONSTRAINT chk_session_temporal_order
    CHECK (
      (revealed_at IS NULL OR revealed_at >= opened_at)
      AND (resolution_opened_at IS NULL OR revealed_at IS NOT NULL)
      AND (resolution_opened_at IS NULL OR resolution_opened_at >= revealed_at)
      AND (closed_at IS NULL OR closed_at >= opened_at)
    )
);

CREATE INDEX IF NOT EXISTS idx_activity_sessions_activity
  ON activity_sessions(activity_id, opened_at DESC);

-- ---------------------------------------------------------------------------
-- 4. One persistent learner trace per anonymous participant per session.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS response_traces (
  id BIGSERIAL PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES activity_sessions(id) ON DELETE CASCADE,
  participant_token_hash TEXT NOT NULL,

  current_option_id TEXT,
  current_confidence INTEGER,

  committed_option_id TEXT,
  committed_confidence INTEGER,
  committed_at TIMESTAMPTZ,

  included_in_reveal BOOLEAN NOT NULL DEFAULT false,

  reveal_encountered_at TIMESTAMPTZ,
  guidance_reached_at TIMESTAMPTZ,

  resolution_state TEXT,
  final_option_id TEXT,
  final_confidence INTEGER,

  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_response_trace_session_participant
    UNIQUE(session_id, participant_token_hash),

  CONSTRAINT chk_response_trace_confidence_positive
    CHECK (
      (current_confidence IS NULL OR current_confidence > 0)
      AND (committed_confidence IS NULL OR committed_confidence > 0)
      AND (final_confidence IS NULL OR final_confidence > 0)
    ),

  CONSTRAINT chk_response_trace_resolution_state
    CHECK (
      resolution_state IS NULL
      OR resolution_state IN (
        'same_more_confident',
        'same_less_confident',
        'same_similar_confidence',
        'different',
        'retain',
        'qualify',
        'revise'
      )
    ),

  CONSTRAINT chk_response_trace_commit_consistency
    CHECK (
      (committed_at IS NULL AND committed_option_id IS NULL AND committed_confidence IS NULL)
      OR
      (committed_at IS NOT NULL AND committed_option_id IS NOT NULL)
    ),

  CONSTRAINT chk_response_trace_reveal_membership
    CHECK (NOT included_in_reveal OR committed_at IS NOT NULL),

  CONSTRAINT chk_response_trace_temporal_order
    CHECK (
      (reveal_encountered_at IS NULL OR committed_at IS NOT NULL)
      AND (guidance_reached_at IS NULL OR reveal_encountered_at IS NOT NULL)
      AND (completed_at IS NULL OR committed_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_response_traces_session
  ON response_traces(session_id);

CREATE INDEX IF NOT EXISTS idx_response_traces_committed_option
  ON response_traces(session_id, committed_option_id)
  WHERE committed_at IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5. Add one canonical, schema-versioned CWD development instance.
-- ---------------------------------------------------------------------------
--
-- The existing legacy row `b1141-w1-least-shared-benefit` is deliberately
-- retained unchanged for rollback. The canonical Stage 3 row below uses the
-- current activity identity/content from the approved Stage 1–2 CWD dossier.
-- It is inserted inactive so the existing application does not start serving it
-- before the backend/frontend have been switched to the Stage 3 engine path.
--
-- No other legacy row is classified automatically. This matters because the
-- legacy repository contains historical activities whose current GEDL model
-- classification may differ from the assumptions under which they were built.

INSERT INTO activities (
  id,
  module,
  week,
  activity,
  sequence,
  question,
  options,
  confidence_points,
  correct_option,
  reveal_mode,
  reveal_threshold,
  cohort_size,
  active,
  model,
  variant,
  title,
  config,
  schema_version
)
VALUES (
  'b1141-w1-who-is-excluded',
  'B1141',
  1,
  'who-is-excluded',
  3,
  'Which of these benefits do you think people have the least equal chance of gaining through sport?',
  '["Better health and wellbeing","A sense of belonging and community","Identity and pride","Opportunities to progress and succeed"]'::jsonb,
  5,
  NULL,
  'manual',
  NULL,
  NULL,
  false,
  'confidence_weighted_response',
  'social_immediate',
  'Who Is Excluded?',
  $config$
  {
    "entry": {
      "text": "Sport is often said to give people important benefits."
    },
    "judgement": {
      "mode": "single",
      "semantics": "categorical",
      "prompt": "Which of these benefits do you think people have the least equal chance of gaining through sport?",
      "options": [
        {"id":"health","label":"Better health and wellbeing","order":1},
        {"id":"belonging","label":"A sense of belonging and community","order":2},
        {"id":"identity","label":"Identity and pride","order":3},
        {"id":"opportunity","label":"Opportunities to progress and succeed","order":4}
      ]
    },
    "evaluation": {
      "mode": "non_keyed",
      "accepted_option_ids": [],
      "reveal_stage": "never"
    },
    "confidence": {
      "enabled": true,
      "prompt": "How confident are you in that judgement?",
      "scale_id": "confidence_5"
    },
    "confrontation": {
      "source": "cohort",
      "reveal_mode": "lecturer_gated",
      "required_outputs": [
        "response_count",
        "judgement_distribution",
        "confidence_by_judgement",
        "overall_confidence",
        "learner_original_position"
      ]
    },
    "guidance": {
      "source": "in_app",
      "content": [
        {
          "type": "bridge",
          "text": "Sport can produce a benefit without giving everyone the same chance to gain it."
        }
      ]
    },
    "resolution": {
      "profile": "confidence_shift",
      "release": "immediate",
      "prompt": "Having seen how the class responded, where are you now?",
      "options": [
        {"id":"same_more_confident","label":"I would keep my answer, but I'm more confident in it","order":1},
        {"id":"same_less_confident","label":"I would keep my answer, but I'm less confident in it","order":2},
        {"id":"same_similar_confidence","label":"I would keep my answer and feel about as confident","order":3},
        {"id":"different","label":"I would choose a different benefit now","order":4}
      ],
      "allow_revised_judgement": true,
      "reassess_confidence": "conditional"
    },
    "lecturer": {
      "pre_reveal_view": "response_count_only",
      "reveal_control": "manual",
      "resolution_control": "immediate",
      "post_reveal_metrics": [],
      "projector_summary": true,
      "reset_session": true
    }
  }
  $config$::jsonb,
  1
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. Indexes useful for configuration lookup.
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_activities_model_active
  ON activities(model, active);

CREATE INDEX IF NOT EXISTS idx_activities_config_gin
  ON activities USING GIN(config);

COMMIT;

-- ---------------------------------------------------------------------------
-- Post-migration verification suggestions (read-only):
-- ---------------------------------------------------------------------------
-- SELECT id, model, variant, schema_version, active, config->'evaluation'
-- FROM activities
-- ORDER BY module, week, sequence, id;
--
-- SELECT id, name, points FROM confidence_scales;
--
-- SELECT id, module, week, activity, question
-- FROM activities
-- WHERE model IS NULL;
--
-- \d activity_sessions
-- \d response_traces
--
-- No application code is switched by this migration alone.
